//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impfverwaltung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Street { get; set; }
        public string Plz { get; set; }
        public string Place { get; set; }
        public Nullable<int> NumVaccinations { get; set; }
        public Nullable<int> VaccinationId { get; set; }
    
        public virtual Vaccination Vaccination { get; set; }
    }
}
